[package]
name = "hello_world"
version = "0.1.0"
authors = ["Nolan Darilek <nolan@thewordnerd.info>"]
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
ndk-glue = "0.7"
tts = { path = "../.." }